	SUBROUTINE LECLIMA
	!THIS SUBROUTINE PREPARES CLIMATE DATA
	USE VARS_MAIN
	IMPLICIT NONE
	INTEGER KLI,MM,IYYY,ID

	!VERIFIES WHICH MONTH IS IT
	CALL caldat(JDIA,MM,id,iyyy)

	DO IC=1,NC
		KLI=ICBOM(IC)

		!AIR TEMPERATURE
		IF(TD(KLI,IT).LT.-200.0.OR.flagaclimed==1)THEN !(TESTS FAILURE=-1.0)
			TA(IC)=TAMM(KLI,MM)	!USES CLIMATOLOGY DATA
		ELSE
			TA(IC)=TD(KLI,IT) !USES DAILY DATA
		ENDIF
		
		!RELATIVE HUMIDITY
		IF(UD(KLI,IT).LT.0.0.OR.flagaclimed==1)THEN !TESTA FALHA (FALHA=-1.0)
			UR(IC)=URMM(KLI,MM) !USES CLIMATOLOGY DATA
		ELSE
			UR(IC)=UD(KLI,IT) !USES DAILY DATA
		ENDIF

		!WIND SPEED
		IF(VD(KLI,IT).LT.0.0.OR.flagaclimed==1)THEN !
			VV(IC)=VVMM(KLI,MM) ! IN M/S
		ELSE
			VV(IC)=VD(KLI,IT) !USES DAILY DATA
		ENDIF	        

		!HOURS OF SUNLIGHT
		IF(SOLD(KLI,IT).LT.0.0.OR.flagaclimed==1)THEN
			SOL(IC)=SOLMM(KLI,MM) !IN HOURS/DAY
		ELSE
			SOL(IC)=SOLD(KLI,IT) !USES DAILY DATA
		ENDIF

		!ATMOSPHERIC PRESSURE 
		IF(PAD(KLI,IT).LT.0.0.OR.flagaclimed==1)THEN
			PA(IC)=PAMM(KLI,MM) 
		ELSE
			PA(IC)=PAD(KLI,IT) !USES DAILY DATA
		ENDIF
	ENDDO

734	FORMAT(5F10.2)
	RETURN
	END