	SUBROUTINE SIMULA

	!ESTA SUBROTINA É CHAMADA QUANDO O PROBLEMA É DE SIMULAÇÃO, NÃO É FEITA A CALIBRAÇÃO
	USE VARS_MAIN
	USE VARS_CALIB
    USE SED_VARS
    USE VARS_CALIB



	IMPLICIT NONE
	INTEGER KB,K
    INTEGER L, KSS  !Counters   Hugo Fagundes 03.07.19
    
    WRITE(FILLOG,*)'Calling initial conditions...'
	CALL CONDINIC


!************ DIOGO BUARQUE ********************
	! ROTINA DE CALCULO DOS PARÂMETROS DA MUSLE
	!*************************************************** Hugo Fagundes 04.07.19 ***************************************************!    
    IF(SED_INDEX==1)THEN
	    CALL SED_INICIAL    
    ENDIF
    !*************************************************** Hugo Fagundes 04.07.19 ***************************************************!    
	
    IF(ICALIB==0)THEN	
        IF(SED_INDEX==1)THEN
	        OPEN(FILSED,FILE  = '.\output\MUSLE_TOTAL.txt',STATUS='UNKNOWN')  !ARQUIVO DE SAIDA COM ACARGA DE SEDIMENTO DA CÉLULA (ton/dia)
	        OPEN(FILSEDa,FILE = '.\output\MUSLE_areia.txt',STATUS='UNKNOWN')  !ARQUIVO DE SAIDA COM ACARGA DE AREIA DA CÉLULA (ton/dia)
	        OPEN(FILSEDs,FILE = '.\output\MUSLE_silte.txt',STATUS='UNKNOWN')  !ARQUIVO DE SAIDA COM ACARGA DE SILTE DA CÉLULA (ton/dia)
	        OPEN(FILSEDc,FILE = '.\output\MUSLE_argila.txt',STATUS='UNKNOWN')  !ARQUIVO DE SAIDA COM ACARGA DE ARGILA DA CÉLULA (ton/dia)
	        OPEN(FILQCE,FILE  = '.\output\QSUP.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A VAZÃO SUPERFICIAL DA CÉLULA (m3/s)
	        OPEN(FILCEL,FILE  = '.\output\QCEL.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A VAZÃO DA CÉLULA (m3/s) 
            OPEN(RIODEP,FILE  = '.\output\DEPdin_RIO.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A QUANTIDADE DE SEDIMENTO DEPOSITADO EM CADA NB EXUTORIOS DESEJADOS Ton/dia
                 !@ ESCREVE CABEÇALHOS
                WRITE(FILSED,'(4A10,<iSEDaux>I15)')  'IT', 'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)  !@ SED_MINI.txt - total (TON/dia)
                WRITE(FILSEDa,'(4A10,<iSEDaux>I15)') 'IT', 'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)  !@ SEDa_MINI.txt - silte (TON/dia)
                WRITE(FILSEDs,'(4A10,<iSEDaux>I15)') 'IT', 'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)  !@ SEDs_MINI.txt - argila (TON/dia)
                WRITE(FILSEDc,'(4A10,<iSEDaux>I15)') 'IT', 'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)  !@ SEDc_MINI.txt - areia (TON/dia)
                WRITE(FILQCE,'(4A10,<iSEDaux>I15)')  'IT', 'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)  !@ QSUP_MINI.txt (m3/s)
                WRITE(FILCEL,'(4A10,<iSEDaux>I15)')  'IT', 'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)  !@ QCEL_MINI.txt (m3/s) 2013_02_06

	        OPEN(RIOCAR,FILE='.\output\CONC_areia.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A CONCENTRAÇÃO DE AREIA SAINDO DOS NB EXUTORIOS DESEJADOS
	        OPEN(RIOCSI,FILE='.\output\CONC_silte.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A CONCENTRAÇÃO DE SILTE SAINDO DOS NB EXUTORIOS DESEJADOS
	        OPEN(RIOCCL,FILE='.\output\CONC_argila.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A CONCENTRAÇÃO DE ARGILA SAINDO DOS NB EXUTORIOS DESEJADOS
        !    OPEN(VAZFLP,FILE='.\output\Q_LATERAL.txt',STATUS='UNKNOWN') !@ DCB_HD_Sed
        !    OPEN(VAZFLP2,FILE='.\output\CFL_FINOS.txt',STATUS='UNKNOWN') !@ DCB_HD_Sed
                !@ ESCREVE CABEÇALHOS
                WRITE(RIOCAR,'(3A10,<iSEDaux>I15)')  'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)   !@ CONC_RIO_areia.txt  (mg/L)
                WRITE(RIOCSI,'(3A10,<iSEDaux>I15)')  'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)   !@ CONC_RIO_silte.txt  (mg/L)
                WRITE(RIOCCL,'(3A10,<iSEDaux>I15)')  'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)   !@ CONC_RIO_argila.txt (mg/L)
        !        WRITE(VAZFLP,'(3A10,<iSEDaux>I15)')  'DIA', 'MES', 'ANO', (CONTIC(IC),IC=1,iSEDaux)   !@ DCB_HD_Sed
        ENDIF
    ENDIF
!************ DIOGO BUARQUE ********************

    
	CALL MODELO !CHAMA A ROTINA QUE COMANDA O LOOP DO TEMPO


!************ DIOGO BUARQUE ********************
	IF(ICALIB==0)THEN	
        IF(SED_INDEX==1)THEN
            CLOSE (FILSED)
	        CLOSE (FILSEDa)
	        CLOSE (FILSEDs)
	        CLOSE (FILSEDc)
	        CLOSE (FILQCE)
	        CLOSE (FILCEL) !@ 2013_02_06
	        CLOSE (TAXPIC)
	
	        CLOSE (RIOCAR)
	        CLOSE (RIOCSI)
	        CLOSE (RIOCCL)
            CLOSE (RIODEP)
        !	CLOSE (VAZFLP)  !@ DCB_HD_Sed


	        OPEN(FILCAR,FILE='.\output\MINI_areia.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A CONCENTRAÇÃO DE AREIA SAINDO DOS EXUTORIOS DESEJADOS
	        OPEN(FILCSI,FILE='.\output\MINI_silte.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A CONCENTRAÇÃO DE SILTE SAINDO DOS EXUTORIOS DESEJADOS
	        OPEN(FILCCL,FILE='.\output\MINI_argila.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A CONCENTRAÇÃO DE ARGILA SAINDO DOS EXUTORIOS DESEJADOS
            IF (FLAG_SEDVAR==1) THEN
               OPEN(FILSSCB,FILE='.\output\MINI_CSS.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A CONCENTRAÇÃO DE SEDIMENTOS EM SUSPENSÃO SAINDO DOS EXUTORIOS DESEJADOS !HUGO FAGUNDES 14/11/19
            ELSEIF(FLAG_SEDVAR==2) THEN
               OPEN(FILSSCB,FILE='.\output\MINI_QSS.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A DESCARGA SÓLIDA DE SEDIMENTOS EM SUSPENSÃO SAINDO DOS EXUTORIOS DESEJADOS !HUGO FAGUNDES 14/11/19
            ELSEIF(FLAG_SEDVAR==3) THEN
               OPEN(FILSSCB,FILE='.\output\MINI_QStot.txt',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM A DESCARGA SÓLIDA TOTAL SAINDO DOS EXUTORIOS DESEJADOS !HUGO FAGUNDES 14/11/19
            ENDIF
            
	            !GRAVA CABEÇALHOS
		        WRITE(FILCAR,'(A10,<NUMSS(AUXCALIBSS)>I15)') 'IT',(ISS(1,KB),KB=1,NUMSS(AUXCALIBSS))
		        WRITE(FILCSI,'(A10,<NUMSS(AUXCALIBSS)>I15)') 'IT',(ISS(1,KB),KB=1,NUMSS(AUXCALIBSS))
		        WRITE(FILCCL,'(A10,<NUMSS(AUXCALIBSS)>I15)') 'IT',(ISS(1,KB),KB=1,NUMSS(AUXCALIBSS))
                WRITE(FILSSCB,'(A10,<NUMSS(AUXCALIBSS)>I15)') 'IT',(ISS(1,KB),KB=1,NUMSS(AUXCALIBSS))
	        DO IT=1,NT
		        !GRAVA CONCENTRACOES NOS NB EXUTORIOS DESEJADOS
		        WRITE(FILCAR,'(I10,<NUMSS(AUXCALIBSS)>F15.3)')IT,(CAREIA(KB,IT),KB=1,NUMSS(AUXCALIBSS))
		        WRITE(FILCSI,'(I10,<NUMSS(AUXCALIBSS)>F15.3)')IT,(CSILTE(KB,IT),KB=1,NUMSS(AUXCALIBSS))
		        WRITE(FILCCL,'(I10,<NUMSS(AUXCALIBSS)>F15.3)')IT,(CARGIL(KB,IT),KB=1,NUMSS(AUXCALIBSS))
                WRITE(FILSSCB,'(I10,<NUMSS(AUXCALIBSS)>F15.3)')IT,(SEDstore(KB,IT,1),KB=1,NUMSS(AUXCALIBSS))
	        ENDDO
	        CLOSE (FILCAR)
	        CLOSE (FILCSI)
	        CLOSE (FILCCL)
            CLOSE (FILSSCB)
        ENDIF
    ENDIF
!************ DIOGO BUARQUE ********************
    CALL FOBJ !CALCULA OS VALORES DAS FUNÇÕES OBJETIVO
    IF(SED_INDEX==1)THEN
	
    CALL SED_Fob_Calib
        IF(ICALIB==0)THEN
	        !GRAVA RESULTADOS DAS FUNÇÕES OBJETIVO EM CADA POSTO
	        DO L=1,NOBS
                WRITE(FILAJU,72)R2(L),R2L(L),ERRV(L)
            ENDDO
            !DO AUXCALIBSS=1,4       !04/10/17
                !CALL SED_Fob_Calib   !04/10/17
                !KSS=AUXCALIBSS      !04/10/17
            DO KSS=1,AUXSS
                DO K=1,NOBSS(KSS)
                    WRITE(FILAJUS,73)SSKGE(K), R2SS(K), ERRVS(K)
                    !WRITE(FILAJUS,73)(SSCORRELAC(K),K=1,NOBSS(KSS))  !04/10/17
                    !WRITE(FILAJUS,73)SSCORRELtemp(KSS), SSCORRELesp(KSS), SSCORRELtudo(KSS)
                    !WRITE(FILAJUS,73)(Resp(K,1),K=1,NOBSS(KSS))
                    !WRITE(FILAJUS,73)(Resp(K,2),K=1,NOBSS(KSS))
        73          FORMAT(<NOBSS(KSS)>F10.3)
                ENDDO
            !ENDDO              
            ENDDO
        ENDIF
    ENDIF

	!GRAVA RESULTADOS DAS FUNÇÕES OBJETIVO EM CADA POSTO
	WRITE(FILAJU,72)(R2(K),K=1,NOBS)
	WRITE(FILAJU,72)(R2L(K),K=1,NOBS)
	WRITE(FILAJU,72)(ERRV(K),K=1,NOBS)

	OPEN(FILBAC,FILE='.\output\BACIAS.HIG',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM DADOS DAS BACIAS
	OPEN(FILPRP,FILE='.\output\QPROP.HIG',STATUS='UNKNOWN') !ARQUIVO DE SAÍDA COM VAZÕES SEGUNDO A ORIGEM
	OPEN(FILHID,FILE='.\output\VAZAO.HIG',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM HIDROGRAMAS CALCULADOS


!************ DIOGO BUARQUE ********************
!       Escreve código da mini-bacia no cabeçalho de cada coluna do VAZAO.HIG
	    WRITE(FILHID,'(A10,<NUMHIDG>I15)') 'IT',(IHIDG(IT),IT=1,NUMHIDG)
!************ DIOGO BUARQUE ********************


	    DO IT=1,NT
		    !GRAVA HIDROGRAMAS NOS NB EXUTORIOS DESEJADOS 
		    WRITE(FILHID,71)IT,(QRG(KB,IT),KB=1,NUMHIDG)
		    !GRAVA VARIÁVEIS CARACTERÍSTICAS DE UMA DAS BACIAS
		    IB=1 !BACIA A SER GRAVADA
		    WRITE(FILBAC,78)WBM(IB,IT),PM2(IB,IT),SIM(IB,IT),EM(IB,IT),DSUM(IB,IT),DINM(IB,IT),DBAM(IB,IT)
		    !GRAVA ARQUIVO COM AS VAZÕES SEGUNDO A ORIGEM
		    WRITE(FILPRP,71)IT,QB(IT),QBI(IT),QBIS(IT)
	    ENDDO
	CLOSE (FILBAC)
	CLOSE (FILHID)
	CLOSE (FILPRP)
	
	!CALCULA PRECIPITAÇÃO MÉDIA ANUAL POR BACIA
	PMB=0.0
	KPM=0
	PM=(PM/NT)*(365.*24.*3600./DTP)

	DO IC=1,NC
		IB=IBAC(IC)
		PMB(IB)=PMB(IB)+PM(IC)*ACEL(IC) !Pondered by the minibasin area
		KPM(IB)=KPM(IB)+ACEL(IC)
	ENDDO
	DO IB=1,NB
		PMB(IB)=PMB(IB)/KPM(IB) !Pondered by the minibasin area
		WRITE(*,*)'Sub-basin ',IB,'   Annual Rainfall',PMB(IB)
		WRITE(FILLOG,*)'Sub-basin ',IB,'   Annual Rainfall',PMB(IB)
    ENDDO
	!FIM DO CALCULO DA PRECIPITAÇÃO MÉDIA ANUAL POR BACIA
	
	
!************ DIOGO BUARQUE set/2012 ********************
!   ESCREVE VAZÕES EM TODAS AS MINI-BACIAS
    OPEN(FILVAZ,FILE='.\output\VAZAO_MINI.HIG',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM HIDROGRAMAS CALCULADOS NAS MINI-BACIAS
        WRITE(FILVAZ,'(A10,<iSEDaux>I15)') 'IT',(CONTIC(IC),IC=1,iSEDaux)        
        DO IT=1,NT
		    WRITE(FILVAZ,'(I10,<iSEDaux>F15.3)')  IT, (Qmini(KB,IT),KB=1,iSEDaux)
	    ENDDO    
    CLOSE (FILVAZ)
!************ DIOGO BUARQUE set/2012 ********************	
		
	
	RETURN

71	FORMAT(I10,<NUMHIDG>F15.3)
72	FORMAT(<NUMHIDG>F10.3)
78	FORMAT(70F10.5)

	END